include("uc_build_problem.jl")
include("uc_run_decision_model.jl")
include("eda/eda_result_decision_model.jl")
# include("uc_run_simulation.jl")
# include("eda/eda_result_simulation.jl")
include("eda/eda_result_generator_power.jl")
include("eda/eda_result_storage_power.jl")
include("plot/plot_result_aggregate.jl")
